version: '3.8'

services:
  app:
    image: python-systemd-app
    container_name: myapp
    ports:
      - "8080:8080"  
    deploy:
      replicas: 1  
    networks:
      - app-network

  app_replica:
    image: python-systemd-app
    container_name: myapp-replica
    ports:
      - "8081:8080"  
    deploy:
      replicas: 1
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
      - app_replica
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
